# Generated by Django 3.2.4 on 2021-09-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=30)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=20)),
            ],
        ),
    ]
